# Generated by Django 3.2.11 on 2022-01-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20220117_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCoin',
            fields=[
                ('coin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coin_krname', models.CharField(max_length=12)),
                ('coin_name', models.CharField(max_length=30)),
                ('coin_image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'vote_coin',
                'managed': False,
            },
        ),
    ]
