# Generated by Django 3.2.11 on 2022-01-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_votecoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('choice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice', models.IntegerField(blank=True, null=True)),
                ('is_answer', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vote_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VoteVote',
            fields=[
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=10)),
                ('finished_at', models.DateTimeField()),
                ('tracked_at', models.DateTimeField()),
                ('created_price', models.IntegerField()),
                ('finished_price', models.IntegerField(blank=True, null=True)),
                ('spent_point', models.IntegerField()),
                ('earned_point', models.IntegerField()),
                ('is_answer', models.IntegerField(blank=True, null=True)),
                ('duration', models.CharField(max_length=10)),
                ('range', models.IntegerField()),
                ('comment', models.CharField(max_length=10)),
                ('pos_participants', models.IntegerField()),
                ('neg_participants', models.IntegerField()),
                ('pos_whales', models.IntegerField()),
                ('neg_whales', models.IntegerField()),
                ('total_participants', models.IntegerField()),
            ],
            options={
                'db_table': 'vote_vote',
                'managed': False,
            },
        ),
    ]
