# Generated by Django 3.2.11 on 2022-02-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_votechoice_votevote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoteChoice',
        ),
        migrations.DeleteModel(
            name='VoteCoin',
        ),
        migrations.DeleteModel(
            name='VoteVote',
        ),
    ]
