# Generated by Django 4.0 on 2022-01-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('coin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=12)),
                ('coin_image', models.URLField()),
                ('cur_price', models.IntegerField()),
                ('trade_date', models.CharField(max_length=10)),
                ('trade_time', models.CharField(max_length=10)),
            ],
        ),
    ]
