# Generated by Django 3.2.11 on 2022-01-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('coin_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('coin_name', models.CharField(max_length=12)),
                ('coin_fullname', models.CharField(max_length=30)),
                ('coin_image', models.URLField()),
                ('cur_price', models.IntegerField()),
                ('trade_date', models.CharField(max_length=10)),
                ('trade_time', models.CharField(max_length=10)),
                ('updated_date', models.IntegerField()),
                ('updated_time', models.IntegerField()),
            ],
        ),
    ]
