# Generated by Django 3.2.11 on 2022-01-10 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='full_updated_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
