# Generated by Django 4.0 on 2022-01-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
